### PR TITLE
Component circular referance (UI solution)

### LINKED ISSUE #1624: MobX Cycle detected in computation Element
## Current Behavior

When selecting the parent component of an element as its component when creating it or from the right panel. `Uncaught Error: [mobx] Cycle detected in computation` error happens

## Expected Behavior

There should be no error.

## More details
So basically, what is happening is that when a component is a child of itself, either direct child, or a child of another component, which is in turn a child of the first component. In other words we're having a cycle in the component tree. Due to this cycle the renderer goes into an infinite loop. In other words, the rendering starts with `renderRoot()`  in `renderer.model.ts` which calls `renderElement()` that creates an `ElementWrapper`. `ElementWrapper` finds the children of the element and calls `renderChildren`, which calls `renderElement()` for each child and from there the recursion continues.

### Two potential solutions exist
1. Modify the renderer so that a component is not rendered more than once if a cycle exists. To do this some metadata can be kept in the rendering pipe or a property can be added to components, but we need to find a way to reset these values after the rendering has finished.
2. Eliminate the components from the drop down in the right panel. This should involve removing every component that has the parent of the currently selected element as a child. Basically for each option we have to check if there is a cycle.

## Steps to Reproduce

Follow the videos:
- first way

https://user-images.githubusercontent.com/51242349/172781487-eb976311-a40b-4329-a9f3-40a666f4aa2e.mp4

- second way

https://user-images.githubusercontent.com/51242349/172781531-1c55ed6b-240e-4f2a-9d1f-0b75f07adc07.mp4

### PR DESCRIPTION
**Pull request by mohasarc**
CLOSES: #1624

## Related Issue(s)
Fixes #1624

### CODE REVIEW

File: libs/frontend/modules/type/src/interface-form/fields/select-component/SelectComponent.tsx [hunk 1]
```diff
@@ -15,8 +21,14 @@ export const SelectComponent = ({ name, error }: SelectComponentProps) => {
     interfaceFormApi.InterfaceForm_GetComponents(),
   )
 
+  // remove the components that refer the current component to avoid creating circular references
+  const filteredComponents = data?.components?.filter(
+    (component) =>
```
Comment (antonmihaylov) [inline libs/frontend/modules/type/src/interface-form/fields/select-component/SelectComponent.tsx:26]: I'm not sure, but do we need to check if `component.id !== activeComponentId` too? I think we do since subgraphAll doesn't return the id of the component itself

**Review by antonmihaylov — CHANGES_REQUESTED** [review]
Overall looking good, just need to check for component.id in SelectComponent and some other minor comments

File: libs/backend/src/repositories/component/getDescendantComponentIds.cypher [hunk 2]
```diff
@@ -0,0 +1,12 @@
+CALL apoc.path.subgraphAll(
+  this,
+  {
+    relationshipFilter: 'COMPONENT_ROOT>|PARENT_OF_ELEMENT>|INSTANCE_OF_COMPONENT>'
+  }
+) YIELD nodes AS descendants
+
+UNWIND descendants AS descendant
+  WITH descendant
+    WHERE NOT 'Element' IN LABELS(descendant)
```
[the remark this answers is not in the document]
Comment (mohasarc) [reply libs/backend/src/repositories/component/getDescendantComponentIds.cypher:10]: Yeah, that makes sense.

File: libs/frontend/modules/type/src/interface-form/fields/select-component/SelectComponent.tsx (hunk 1 above)
Comment (mohasarc) [reply libs/frontend/modules/type/src/interface-form/fields/select-component/SelectComponent.tsx:26]: Actually, subgraphAll does return the current component id as well.

Comment (antonmihaylov) [reply libs/frontend/modules/type/src/interface-form/fields/select-component/SelectComponent.tsx:26]: Oh good, in the examples in the docs they don't have it, but maybe they've omitted it for illustration

**Review by antonmihaylov — APPROVED** [review]
